### ISSUE TITLE
Special Stage Maker; unable to go past certain boundaries and undeletable objects

### ISSUE THREAD

**Issue by AmeBleu** [ElspethThePict/S1Forever#12]
This is kind of hard to explain, but, In the special stage maker, if you place objects past a certain boundary and then leave the special stage maker, the objects will disappear and some will become undeletable.

https://github.com/user-attachments/assets/28af4efa-8acc-467f-bf51-10743026b804

**Comment by ElspethThePict** [comment]
Nice catch, thanks for the heads up.
