### ISSUE TITLE
Buttons in "Data" section don't work properly

### ISSUE THREAD

**Issue by Eggmanplant** [ElspethThePict/S1Forever#8]
If I preess and hold "Delete Arcade Mode records" in Options/Data, the Arcade Mode records aren't deleted. Same thing for other buttons too. Tested on Android with APK manually built from latest commit on my PC. The game is also latest commit from this repo. Also the "Delete Secrets data" button doesn't have touch controls.

**Comment by ElspethThePict** [comment]
To clarify, none of the data management buttons are working?

Do they react to your touch or are they simply doing nothing?

**Comment by Eggmanplant** [comment]
They react. None work.

**Comment by ElspethThePict** [comment]
Fixed as of commit 345dbd9
